# Generated by Django 5.0.1 on 2024-01-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='email_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
