# Generated by Django 5.0.1 on 2024-01-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_description_room_participants_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='chat_rooms', to='chat.chatuser'),
        ),
    ]
